name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
      - name: Build binary
        run: |
          chmod +x scripts/buildprod.sh
          ./scripts/buildprod.sh
      - name: List build artifacts
        run: ls -lh notely || echo "Binary not built"
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GAR_REGION }}-docker.pkg.dev --quiet
      - name: Cloud Build submit (commit + latest tags)
        id: cloud_build
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GAR_REGION }}
          REPOSITORY: ${{ secrets.GAR_REPOSITORY }}
          IMAGE_NAME: notely
        run: |
          set -euo pipefail
          COMMIT_IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${GITHUB_SHA}"
          LATEST_IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest"
          echo "Submitting Cloud Build with images: $COMMIT_IMAGE and $LATEST_IMAGE"
          gcloud builds submit \
            --project "$PROJECT_ID" \
            --tag "$COMMIT_IMAGE" \
            --tag "$LATEST_IMAGE" \
            .
          echo "commit_image=$COMMIT_IMAGE" >> $GITHUB_OUTPUT
          echo "latest_image=$LATEST_IMAGE" >> $GITHUB_OUTPUT
      - name: Show built image references
        run: |
          echo "Commit image: ${{ steps.cloud_build.outputs.commit_image }}"
          echo "Latest image: ${{ steps.cloud_build.outputs.latest_image }}"
      - name: List images in Artifact Registry (debug)
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GAR_REGION }}
          REPOSITORY: ${{ secrets.GAR_REPOSITORY }}
        run: |
          echo "Listing images after push..."
          gcloud artifacts docker images list "$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY" --project "$PROJECT_ID" || echo "List failed"
      - name: List tags for image (debug)
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GAR_REGION }}
          REPOSITORY: ${{ secrets.GAR_REPOSITORY }}
        run: |
          echo "Listing tags for notely image..."
          gcloud artifacts docker tags list "$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/notely" --project "$PROJECT_ID" || echo "Tag list failed"
