name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
      - name: Build binary
        run: |
          chmod +x scripts/buildprod.sh
          ./scripts/buildprod.sh
      - name: List build artifacts
        run: ls -lh notely || echo "Binary not built"
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
      - name: Cloud Build submit (latest tag)
        env:
          IMAGE_URI: ${{ secrets.GAR_IMAGE_URI }}
        run: |
          set -euo pipefail
          echo "Building and pushing image: $IMAGE_URI"
          gcloud builds submit --tag "$IMAGE_URI" .
      - name: Output image reference
        run: echo "Image pushed: ${{ secrets.GAR_IMAGE_URI }}"
