name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
      - name: Build binary
        run: |
          chmod +x scripts/buildprod.sh
          ./scripts/buildprod.sh
      - name: List build artifacts
        run: ls -lh notely || echo "Binary not built"
