name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
      - name: Build binary
        run: |
          chmod +x scripts/buildprod.sh
          ./scripts/buildprod.sh
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
      - name: Build and push image (Cloud Build)
        run: |
          set -euo pipefail
          if [ -z "${{ secrets.GAR_IMAGE_URI }}" ]; then
            echo "::error:: Missing GAR_IMAGE_URI secret. Set it in repo settings."
            exit 1
          fi
          echo "gcloud builds submit --tag ${{ secrets.GAR_IMAGE_URI }} ."
          gcloud builds submit --tag "${{ secrets.GAR_IMAGE_URI }}" .
          echo "Image pushed: ${{ secrets.GAR_IMAGE_URI }}"
