name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy (placeholder)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Show commit
        run: |
          echo "Deploy pipeline triggered on main commit: $GITHUB_SHA"
          echo "(Placeholder) Add deployment steps here later."
